using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NzWalks.API.Data;
using NzWalks.API.Models.DTOs;
using NzWalks.API.Models.Domain;
using Microsoft.EntityFrameworkCore;
using NzWalks.API.Repositries;
using AutoMapper;

namespace NzWalks.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RegionController : ControllerBase
    {
        private readonly NzWalksDbContext _dbContext;
        private IRepositry _regionRepository;
        private IMapper _mapper;

        public RegionController(NzWalksDbContext dbContext , IRepositry regionRepository, IMapper mapper)
        {
            _dbContext = dbContext; 
            _regionRepository = regionRepository;
            _mapper = mapper;
        }

        [HttpGet]
        //public IActionResult GetAllRegions()
        public async Task<IActionResult> GetAllRegions()
        {
            // get all regions from the database
            //var regionsDomainModel = _dbContext.Regions.ToList();

            var regionsDomainModel = await _regionRepository.GetAllRegionsAsync();

            // regiondto
            //var regionDtos=new List<RegionDto>();
            //foreach (var regionDomain in regionsDomainModel)
            //{
            //    regionDtos.Add(new RegionDto
            //    {
            //        Id = regionDomain.Id,
            //        Name = regionDomain.Name,
            //        Code = regionDomain.Code,
            //        RegionImageUrl = regionDomain.RegionImageUrl,

            //    });
            //}

            //short way to convert domain model to dto using automapper
            var regionDtos = _mapper.Map<List<RegionDto>>(regionsDomainModel);

            return Ok(regionDtos);
        }

        [HttpGet]
        [Route("{id:guid}")]
       // public IActionResult GetRegionById([FromRoute] Guid id)
        public async Task<IActionResult> GetRegionById([FromRoute] Guid id)
        {
            var regionDomain = await _regionRepository.GetRegionByIdAsync(id);
            if (regionDomain == null)
            {
                return NotFound();
            }

            //regiondto
            //var regionDto = new RegionDto
            //{
            //    Id = regionDomain.Id, 
            //    Name = regionDomain.Name,
            //    Code = regionDomain.Code,
            //    RegionImageUrl = regionDomain.RegionImageUrl,
            //};
            //short short way to convert domain model to dto using automapper(its reverse we are using mapper here to reduce code
            var regionDto = _mapper.Map<RegionDto>(regionDomain);

            return Ok(regionDto);
        }


         /// <summary>
        /// Creates a new region.
        /// </summary>
        /// <param name="addregionDto">DTO containing data for the region to create.</param>
        /// <returns>Returns 201 Created with the created RegionDto, or 400 Bad Request if input is invalid.</returns>
        [HttpPost]
        public async Task<IActionResult> CreateRegion([FromBody] AddRegionDto addregionDto)
        {
            if (ModelState.IsValid)
            {
                // Validate input
                if (addregionDto == null)
                {
                    return BadRequest();
                }

                // Map DTO to Domain model
                var regionDomain = new Regions
                {
                    // Id is usually generated by the DB (e.g., GUID) so don't set it here
                    Name = addregionDto.Name,
                    Code = addregionDto.Code,
                    RegionImageUrl = addregionDto.RegionImageUrl
                };

                // Persist to database
                await _dbContext.Regions.AddAsync(regionDomain);
                await _dbContext.SaveChangesAsync();

                // Map saved domain model to DTO to return (ensure Id populated)
                var regionDto = new RegionDto
                {
                    Id = regionDomain.Id,
                    Name = regionDomain.Name,
                    Code = regionDomain.Code,
                    RegionImageUrl = regionDomain.RegionImageUrl
                };

                // Return 201 Created with location header pointing to GetRegionById
                return CreatedAtAction(nameof(GetRegionById), new { id = regionDomain.Id }, regionDto);
            }
            else
            {
                return BadRequest(ModelState);
            }
        }


        [HttpPut]
        [Route("{id:guid}")]
       // public IActionResult Update([FromRoute] Guid id, [FromBody] UpdateRegionDto updateRegionDto)
        public async Task<IActionResult> Update([FromRoute] Guid id, [FromBody] UpdateRegionDto updateRegionDto)
        {
            var regionDomainModel = await _dbContext.Regions.FindAsync(id);
            if(regionDomainModel == null)
            {
                return NotFound();
            }

            //Map DTO to Domain Model
            regionDomainModel.Code = updateRegionDto.Code;
            regionDomainModel.Name = updateRegionDto.Name;
            regionDomainModel.RegionImageUrl = updateRegionDto.RegionImageUrl;

            await _dbContext.SaveChangesAsync();


            //convet    Domain model to DTO

            var regiondto = new RegionDto
            {
                Id = regionDomainModel.Id,
                Code = regionDomainModel.Code,
                Name = regionDomainModel.Name,
                RegionImageUrl = regionDomainModel.RegionImageUrl
            };

            return Ok(regiondto);
               

        }

        [HttpDelete]
        [Route("{id:Guid}")]
        //public IActionResult Delete([FromRoute] Guid id)
        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            var regionDomainModel = await _dbContext.Regions.FindAsync(id);
            if(regionDomainModel == null)
            {
                return NotFound();

            }

            //delte region

            _dbContext.Regions.Remove(regionDomainModel);
            await _dbContext.SaveChangesAsync();

            //return deleted region back
            //map doman to dto

            var regiondto = new Regions
            {
                Id = regionDomainModel.Id,
                Code = regionDomainModel.Code,
                Name = regionDomainModel.Name,
                RegionImageUrl = regionDomainModel.RegionImageUrl
            };

            return Ok(regiondto);


        }
    }
}
